// src/components/Projects.vue
<script setup>
import { onMounted, reactive } from 'vue'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger.js'
import { Collapse } from '../lib/collapse'
import { projects as projectData } from '../data.json'

gsap.registerPlugin(ScrollTrigger)

const projects = reactive(
  projectData.map(({ id, title, description, year, role, image, url }, index) => ({
    title,
    description,
    year,
    role,
    image,
    url,
    isExpanded: false,
  }))
)

function handleAccordion(selectedIndex) {
  projects.forEach((_, index) => {
    projects[index].isExpanded = index === selectedIndex ? !projects[index].isExpanded : false
  })
}

onMounted(() => {
  // reveal project list on scroll
  gsap.from('.projects-label', {
    duration: 0.3,
    x: 20,
    opacity: 0,
    scrollTrigger: { start: 2, end: 3, toggleActions: 'play none none reverse' },
  })
  gsap.from('.project-item', {
    duration: 0.3,
    delay: 0.6,
    x: 20,
    opacity: 0,
    stagger: 0.05,
    scrollTrigger: { start: 2, end: 3, toggleActions: 'play none none reverse' },
  })

  // reveal project images on title hover
  let targets = gsap.utils.toArray('.project-item')
  targets.forEach((el, index) => {
    const text = el.querySelector('.project-title')
    const image = el.querySelector('.project-image')

    text.addEventListener('mouseenter', (e) => {
      gsap.to(image, { autoAlpha: 1 })
    })

    text.addEventListener('mouseleave', (e) => {
      gsap.to(image, { autoAlpha: 0 })
    })

    text.addEventListener('mousemove', (e) => {
      gsap.set(image, {
        x: e.offsetX,
        y: e.offsetY,
        xPercent: -100,
        yPercent: -10 * (index + 1),
        stagger: 0.05,
      })
    })
  })
})
</script>

<template>
  <div class="projects">
    <h5 class="projects-label">Projects</h5>
    <div v-for="(project, index) in projects" :key="project.title" class="project-item">
      <div
        class="project-title"
        :class="[
          'panel',
          {
            Active: project.isExpanded,
            'text-green': project.isExpanded,
          },
        ]"
        @click="handleAccordion(index)"
      >
        <span>{{ project.title }}</span>
        <img :src="project.image" alt="" class="project-image" />
      </div>

      <Collapse as="section" :when="project.isExpanded" class="v-collapse">
        <div class="project-details">
          <img :src="project.image" alt="" class="project-thumbnail" />
          <p>{{ project.description }} — {{ project.year }}: {{ project.role }}</p>
          <p>
            <a :href="project.url" target="_blank">visit site <span class="text-[14px]">↗</span></a>
          </p>
        </div>
      </Collapse>
    </div>
  </div>
</template>

<style scoped>
.projects {
  @apply p-10 text-right overflow-hidden mb-20;
}

.project-item {
  @apply relative text-right flex flex-col items-end;
}

.project-title {
  @apply leading-none text-3xl xl:text-5xl font-display transition ease-in-out duration-300 cursor-pointer select-none flex items-center uppercase;
}

.project-item:hover .project-title {
  @apply text-green;
}

.project-thumbnail {
  @apply md:hidden block my-4;
}

.project-image {
  @apply hidden md:block md:w-[440px] xl:w-[720px] opacity-0 absolute left-1/2 top-1/2 -translate-y-[-50%] -translate-x-[-50%] pointer-events-none;
}

.project-details {
  @apply flex flex-col items-end text-right m-0 pb-5;
}

.project-details p {
  @apply text-[12px] max-w-[350px] mb-2;
}
</style>

// app/components/Projects.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { projects } from '@/app/data';

gsap.registerPlugin(ScrollTrigger);

export default function Projects() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const listRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = listRef.current;
    if (!el) return;

    const items = el.querySelectorAll('.project-item');
    gsap.set(items, { y: 40, opacity: 0, filter: 'blur(6px)' });

    const tween = gsap.to(items, {
      y: 0,
      opacity: 1,
      filter: 'blur(0px)',
      duration: 0.5,
      stagger: 0.06,
      ease: 'power3.out',
      scrollTrigger: {
        trigger: el,
        start: 'top 80%',
        once: true,
      },
    });

    return () => {
      tween.scrollTrigger?.kill();
      tween.kill();
    };
  }, []);

  return (
    <section id="projects" className="mt-24 min-h-dvh px-4 py-24">
      <div className="grid grid-cols-1 md:grid-cols-4">
        <div ref={listRef} className="space-y-1 text-right md:col-span-3 md:col-start-2 md:-space-y-2">
          {projects.map((project, i) => {
            const isOpen = openIndex === i;
            return (
              <div key={i} className="project-item" style={{ opacity: 0 }}>
                <button
                  onClick={() => setOpenIndex(isOpen ? null : i)}
                  className="block w-full py-1 text-right md:py-0.5"
                >
                  <span
                    className={`font-serif text-3xl leading-none tracking-tight uppercase transition-colors duration-300 hover:text-white md:text-5xl lg:text-6xl ${isOpen ? 'text-white' : 'text-neutral-500'}`}
                  >
                    {project.title}
                  </span>
                </button>

                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: [0.25, 0.1, 0.25, 1] }}
                      className="overflow-hidden"
                    >
                      <div className="pt-3 pb-6 text-right md:pb-8">
                        <p className="font-sans text-sm leading-relaxed tracking-tight">
                          {project.description}
                        </p>
                        <div className="mt-4 flex flex-wrap justify-end items-baseline gap-x-6 gap-y-2">
                          <span className="font-mono text-[10px] text-neutral-500 uppercase">
                            {project.role}
                          </span>
                          <span className="font-mono text-[10px] text-neutral-500 uppercase">
                            {project.technologies}
                          </span>
                        </div>
                        <a
                          href={project.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="mt-4 inline-block font-mono text-[10px] tracking-widest text-neutral-500 uppercase transition-colors hover:text-white"
                        >
                          Visit &rarr;
                        </a>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
