// app/components/Footer.tsx
export default function Footer() {
  const currentYear = new Date().getFullYear();
  return (
    <footer className="text-muted-foreground grid grid-cols-2 items-center p-4 font-mono text-[10px] uppercase md:grid-cols-4">
      <div>&copy; {currentYear}</div>
      <div className="hidden md:block md:col-start-3">
        &rarr;&nbsp;
        <a href="mailto:m@ciccarel.li" className="hover:text-foreground transition-colors">
          m@ciccarel.li
        </a>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="grid grid-cols-2 md:grid-cols-3 gap-4">
    <div class="p-10">
      <p class="mb-0">freelance developer<br />bk, ny</p>
    </div>
    <div class="p-10">
      <p class="mb-0 text-right md:text-center">
        <a href="mailto:mikecicc@gmail.com">Email</a> — <a href="https://twitter.com/mciccarelli">Twitter</a> <br />
        <a href="https://github.com/mciccarelli">Github</a>
      </p>
    </div>
    <div class="hidden md:block p-10 md:col-span-1">
      <p class="mb-0 text-center md:text-right">All Rights reserved. <br />Michael Ciccarelli &copy; 2023</p>
    </div>
  </footer>
</template>
